# Build settings
markdown: kramdown
# Site settings
title: Hardened GNU/Linux
logo: /images/hardenedlinux-black-logo.png
email: contact@hardenedlinux.org
description: > # this means to ignore newlines until "baseurl:"
  We are a group of free software enthusiasts, anarchists, cyber security researchers. Long live anarchy! Long live 0ld sch00l!!! A small step in security hardening --> A giant leap in Free & Open source software!!!

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hardenedlinux.org" # the base hostname & protocol for your site
twitter_username: hardenedlinux
github_username:  hardenedlinux
google_groupname:  hardenedlinux

# Build settings
markdown: kramdown
paginate: 7
paginate_path: "/page:num/"
